# Generated by Django 3.2 on 2022-04-10 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0002_initial")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="feedin_cap",
            field=models.FloatField(
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        )
    ]
