# Generated by Django 3.2 on 2022-05-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0004_alter_project_user")]

    operations = [
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.project",
                    ),
                )
            ],
            bases=("projects.project",),
        )
    ]
