# Generated by Django 3.2 on 2022-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0006_asset_efficiency_multiple")]

    operations = [
        migrations.AlterField(
            model_name="asset", name="efficiency", field=models.TextField(null=True)
        )
    ]
