# Generated by Django 3.2 on 2022-09-28 20:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0007_alter_asset_efficiency")]

    operations = [
        migrations.CreateModel(
            name="COPCalculator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_high", models.TextField()),
                ("temperature_low", models.TextField()),
                (
                    "temp_threshold_icing",
                    models.FloatField(
                        default=2,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(-273.15)],
                    ),
                ),
                (
                    "quality_grade",
                    models.FloatField(
                        default=1,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "factor_icing",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("Heat pump", "heat_pump"), ("Chiller", "chiller")],
                        max_length=20,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.asset",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.scenario",
                    ),
                ),
            ],
        )
    ]
