# Generated by Django 3.2.15 on 2022-10-14 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0008_copcalculator")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="fixed_thermal_losses_absolute",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="fixed_thermal_losses_relative",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="thermal_loss_rate",
            field=models.FloatField(
                null=True, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
