# Generated by Django 3.2.15 on 2022-10-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0009_thermal_stratified_storage")]

    operations = [
        migrations.AlterField(
            model_name="asset", name="energy_price", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="asset", name="feedin_tariff", field=models.TextField(null=True)
        ),
    ]
