# Generated by Django 3.2.15 on 2022-11-04 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0010_make_feedin_and_price_scalar_or_series")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="crate",
            field=models.FloatField(
                default=1,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="feedin_cap",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="maximum_capacity",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
