# Generated by Django 3.2.16 on 2022-11-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0012_auto_20221108_1741")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="balanced",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False, null=True
            ),
        )
    ]
