# Generated by Django 3.2.16 on 2022-11-22 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0016_auto_20221121_1951")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="fixed_thermal_losses_absolute",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="fixed_thermal_losses_relative",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="thermal_loss_rate",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
