# Generated by Django 3.2.16 on 2022-11-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0017_auto_20221122_1453")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="input_timeseries",
            field=models.TextField(blank=True, null=True),
        )
    ]
