# Generated by Django 3.2.16 on 2022-12-08 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0020_asset_choice_load_profile")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="invest_relation_input_capacity",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="invest_relation_output_capacity",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
