# Generated by Django 3.2.16 on 2022-12-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0021_auto_20221208_1925")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="eco_params_flow_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("inputs", "Relate parameters to the Input-Flow"),
                    ("outputs", "Relate parameters to the Output-Flow"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="emission_factor",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="tec_params_flow_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("inputs", "Relate parameters to the Input-Flow"),
                    ("outputs", "Relate parameters to the Output-Flow"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="fixed_thermal_losses_absolute",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="fixed_thermal_losses_relative",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
