# Generated by Django 3.2.16 on 2022-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0022_auto_20221214_1327")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="renewable_factor",
            field=models.FloatField(blank=True, default=None, null=True),
        )
    ]
