# Generated by Django 3.2.7 on 2023-02-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0023_asset_renewable_factor")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="oep_column_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="oep_table_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
