# Generated by Django 3.2.7 on 2023-03-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0027_auto_20230322_1546")]

    operations = [
        migrations.AlterField(
            model_name="inputparametersuggestion",
            name="input_timeseries",
            field=models.TextField(blank=True, null=True),
        )
    ]
