# Generated by Django 3.2.7 on 2023-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_alter_inputparametersuggestion_input_timeseries")
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="source_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("Wind", "Wind power plant"),
                    ("Photovoltaic Free Field", "Photovoltaic Free Field"),
                    ("Import Grid", "Import from the power grid"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="year_choice",
            field=models.IntegerField(
                choices=[
                    ("", "Choose..."),
                    (2025, "2025"),
                    (2030, "2030"),
                    (2035, "2035"),
                    (2040, "2040"),
                    (2045, "2045"),
                ],
                null=True,
            ),
        ),
    ]
