# Generated by Django 3.2.7 on 2023-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0029_auto_20230323_1644")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="trafo_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("Biogas CHP", "Biogas CHP"),
                    (
                        "Biogas injection (New facility)",
                        "Biogas injection (New facility)",
                    ),
                    ("Gas and steam power plant", "Gas and steam power plant"),
                    ("Power to Liquid", "Power to Liquid"),
                    ("Methanisation", "Methanisation"),
                    ("Electrolysis", "Electrolysis"),
                    ("Fuel cell", "Fuel cell"),
                    (
                        "Air source heat pump (large-scale)",
                        "Air source heat pump (large-scale)",
                    ),
                    ("Electrode heating boiler", "Electrode heating boiler"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="year_choice",
            field=models.IntegerField(
                choices=[
                    ("", "Choose..."),
                    (2025, 2025),
                    (2030, 2030),
                    (2035, 2035),
                    (2040, 2040),
                    (2045, 2045),
                ],
                null=True,
            ),
        ),
    ]
