# Generated by Django 3.2.7 on 2023-05-02 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0030_auto_20230502_1605")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="efficiency_el",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="efficiency_th",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
