# Generated by Django 3.2.7 on 2023-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0031_auto_20230502_1620")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="efficiency",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="trafo_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("Biogas CHP", "Biogas CHP"),
                    (
                        "Biogas injection (New facility)",
                        "Biogas injection (New facility)",
                    ),
                    ("GuD", "Gas and steam power plant"),
                    ("PtL", "Power to Liquid"),
                    ("Methanisation", "Methanisation"),
                    ("Electrolysis", "Electrolysis"),
                    ("Fuel cell", "Fuel cell"),
                    (
                        "Air source heat pump (large-scale)",
                        "Air source heat pump (large-scale)",
                    ),
                    ("Electrode heating boiler", "Electrode heating boiler"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
