# Generated by Django 3.2.7 on 2023-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0032_auto_20230502_1951")]

    operations = [
        migrations.RenameField(
            model_name="asset", old_name="year_choice", new_name="year_choice_source"
        ),
        migrations.AddField(
            model_name="asset",
            name="year_choice_trafo",
            field=models.IntegerField(
                choices=[
                    ("", "Choose..."),
                    (2025, 2025),
                    (2030, 2030),
                    (2035, 2035),
                    (2040, 2040),
                    (2045, 2045),
                ],
                null=True,
            ),
        ),
    ]
