# Generated by Django 3.2.7 on 2023-05-16 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_auto_20230515_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="interest_rate",
            field=models.FloatField(
                null=True, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
