# Generated by Django 3.2.7 on 2023-05-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_scenario_interest_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="economic_data",
        ),
    ]
