# Generated by Django 3.2.7 on 2023-05-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0042_auto_20230516_1936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="type",
        ),
    ]
