# Generated by Django 3.2.7 on 2023-06-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20230607_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='year_choice_source',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='year_choice_storage',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='year_choice_trafo',
        ),
    ]
