# Generated by Django 3.2.7 on 2023-07-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0048_auto_20230627_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="type",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("Electricity", "Electricity"),
                    ("Heat", "Heat"),
                    ("Gas", "Gas"),
                    ("H2", "H2"),
                ],
                default="Electricity",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="source_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("Wind", "Wind power plant"),
                    ("Photovoltaic Free Field", "Ground Mounted Photovoltaic"),
                    ("Import Grid", "Import from the power grid"),
                    ("Biomass supply", "Biomass supply"),
                    ("Other", "Other"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="economicdata",
            name="currency",
            field=models.CharField(
                choices=[("", "Choose..."), ("EUR", "EUR")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="unit_choice",
            field=models.CharField(
                choices=[("", "Choose..."), ("MW/MWh", "MW/MWh")],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="unit_choice_co2",
            field=models.CharField(
                choices=[("", "Choose..."), ("t CO2", "t CO2")],
                max_length=40,
                null=True,
            ),
        ),
    ]
