# Generated by Django 3.2.7 on 2023-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_scenario_trafo_input_output_variation_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenario",
            name="trafo_input_output_variation_choice",
        ),
    ]
