# Generated by Django 3.2.7 on 2023-08-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0052_remove_scenario_trafo_input_output_variation_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="trafo_input_output_variation_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("1:1", "1 input: 1 output"),
                    ("1:2", "1 input: 2 outputs"),
                    ("2:3", "2 inputs: 3 outputs"),
                    ("3:3", "3 inputs: 3 outputs"),
                    ("2:1", "2 inputs: 1 output"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
