# Generated by Django 3.2.7 on 2023-08-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_auto_20230814_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trafo_output_bus_1',
            field=models.CharField(choices=[], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='trafo_output_bus_2',
            field=models.CharField(blank=True, choices=[], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='trafo_output_bus_3',
            field=models.CharField(blank=True, choices=[], max_length=128, null=True),
        ),
    ]
