# Generated by Django 3.2.7 on 2023-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_alter_asset_trafo_input_conversionf_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='trafo_input_bus_1',
            field=models.CharField(default='Choose', max_length=128),
        ),
    ]
