# Generated by Django 4.2.4 on 2023-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0068_auto_20230815_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="user_mode_choice",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("Default User", "Default User"),
                    ("Expert", "Expert"),
                ],
                default="Default User",
                max_length=40,
                null=True,
            ),
        ),
    ]
