FROM python:3.10

ENV APP_ROOT /src
ENV CONFIG_ROOT /config
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir ${CONFIG_ROOT}
COPY requirements/requirements.txt ${CONFIG_ROOT}/requirements.txt
COPY requirements/InRetEnsys-0.2a7-py3-none-any.whl ${CONFIG_ROOT}/InRetEnsys-0.2a7-py3-none-any.whl

RUN pip install --upgrade pip
RUN pip install -r ${CONFIG_ROOT}/requirements.txt
RUN pip install --upgrade ${CONFIG_ROOT}/InRetEnsys-0.2a7-py3-none-any.whl

WORKDIR ${APP_ROOT}

COPY . ${APP_ROOT}

CMD ["python", "manage.py", "collectstatic", "--no-input"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]