# Generated by Django 3.2.16 on 2022-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0002_initial")]

    operations = [
        migrations.AlterField(
            model_name="sensitivityanalysisgraph",
            name="y",
            field=models.CharField(choices=[], max_length=50),
        )
    ]
