# Generated by Django 3.2.15 on 2023-01-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0003_alter_sensitivityanalysisgraph_y")]

    operations = [
        migrations.AlterField(
            model_name="sensitivityanalysisgraph",
            name="y",
            field=models.CharField(
                choices=[
                    ("annual_total_flow", "Aggregated flow"),
                    (
                        "annuity_om",
                        "Annual operation, maintenance and dispatch expenses",
                    ),
                    ("annuity_total", "Annuity"),
                    ("average_flow", "Average flow"),
                    ("costs_cost_om", "Operation and maintenance costs"),
                    ("costs_dispatch", "Dispatch costs"),
                    ("costs_investment_over_lifetime", "Investment costs"),
                    ("costs_om_total", "Operation, maintenance and dispatch costs"),
                    ("costs_total", "Net Present Costs (NPC)"),
                    ("costs_upfront_in_year_zero", "Upfront investment costs"),
                    ("flow", "Dispatch of an asset"),
                    (
                        "levelized_cost_of_energy_of_asset",
                        "Levelized cost of throughput",
                    ),
                    ("optimizedAddCap", "Optimal additional capacity"),
                    ("peak_flow", "Peak flow"),
                    ("replacement_costs_during_project_lifetime", "Replacement costs"),
                    ("total_emissions", "Total GHG emissions"),
                ],
                max_length=50,
            ),
        )
    ]
