# Generated by Django 3.2.7 on 2023-02-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0004_alter_sensitivityanalysisgraph_y")]

    operations = [
        migrations.AlterField(
            model_name="sensitivityanalysisgraph",
            name="y",
            field=models.CharField(choices=[], max_length=50),
        )
    ]
