FROM python:3.12

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV APP_ROOT /app
ENV INSTALL_ROOT /requirements

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install git libpq-dev gcc libc-dev libhdf5-dev
RUN apt-get -y install python3-h5py

RUN apt autoclean

RUN mkdir ${INSTALL_ROOT}
COPY requirements/ ${INSTALL_ROOT}

RUN pip install --upgrade pip
RUN pip install -r ${INSTALL_ROOT}/requirements.txt
RUN pip install --upgrade ${INSTALL_ROOT}/InRetEnsys-0.2a7-py3-none-any.whl

COPY api/ ${APP_ROOT}/

WORKDIR ${APP_ROOT}/

CMD ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8001"]
